### ISSUE TITLE
Allow for "Build Trigger" timezone to be configured

### ISSUE THREAD

**Issue by clayellis-cricut** [amrfarid140/bitrise-step-microsoft-teams-integration#28]
The "Build Triggered" fact is always displayed in UTC time. It would be nice to allow this to be configured to a custom time zone.

**Comment by jamieastley** [comment]
This should be a relatively easy addition.

What are your thoughts on user input for this? The options are either:

* Setting all the possible timezone names as `value_options` values in the `step.yml` to allow for dropdown list selection within the Bitrise workflow editor
* Free text input that relies on the user to input the correct value (eg. `America/Los Angeles`, but will default to UTC if a value is not defined for backwards compatibility.

I'm leaning towards the latter because while the former is a bit more user friendly and has `value_options` validation provided by Bitrise, it feels pretty gross to have to list every timezone name within `step.yml`..

**Comment by clayellis-cricut** [comment]
I would tend to agree with the latter. To make it a little easier for users to discover valid values, we could include in the input description something like "Valid values can be found by running `systemsetup -listtimezones`" (there might be a better, more portable command.)

**Comment by jamieastley** [comment]
Will include this additional input in the `2.1.0` release after #30 is merged.
